### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by toonjoey** [ponyboy837/TTI-Leak--From-2015-#1]
astron:

'astrond' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\[censored]\Desktop\TTTeststuff\src\astron>

UberDOG:
DCFile::read of astron/dclass/otp.dc
DCFile::read of astron/dclass/toon.dc
OTPLocalizer: Running in language: english
TTLocalizer: Running in language: english
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\[censored]\Desktop\TTTeststuff\src\toontown\uberdog\ServiceStart.py", line 41, in <module>
    config.GetInt('air-stateserver', 4002))
  File "toontown\uberdog\ToontownUberRepository.py", line 21, in __init__
    ToontownInternalRepository.__init__(self, baseChannel, serverId, dcSuffix='UD')
  File "toontown\distributed\ToontownInternalRepository.py", line 14, in __init__
    self.netMessenger.register(0, 'shardStatus')
AttributeError: 'ToontownUberRepository' object has no attribute 'netMessenger'

AI is the same as UberDOG, and the game is normal.

Help please?

**Comment by toonjoey** [comment]
Whoops, didn't read the README, sorry 'bout that. :-1:

It seems to not be able to load the cattlelog GUI for some odd reason, I think you guys forgot to add the .bam extension. I'll fix that.

**Comment by MrExternal** [comment]
> 'astrond' is not recognized as an internal or external command,
operable program or batch file.

This is because it cannot find astrond.exe. 
Also, on the topic of the ToontownUberRepository, I am sure that is a side-effect of Astron not working.

**Comment by MrExternal** [comment]
> It seems to not be able to load the cattlelog GUI for some odd reason

This is something to do with the model itself (or so I think). 
I'll try and look into this issue.

**Comment by toonjoey** [comment]
alright thanks there buddy chum pal friend pal amigo bro homeslice breadslice dawg

Seriously, thanks for looking into it, I've been looking into it myself! Don't think the model is in the phase files.

**Comment by toonjoey** [comment]
This is so frustrating, I've tried removing the filepath and NO LUCK!

**Comment by ponyboy837** [comment]
I dunno what to say. But i can say it works for me. Probably because it may require a custom panda3d which i no longer have.....

**Comment by toonjoey** [comment]
Do I need to have the phase files in a directory of some sort? (Like C:/Panda3D-1.9.0/models)

**Comment by JohnathanUnknown** [comment]
@toonjoey I think so, not really sure but I think Pony is on to something. 

I can attempt to find my version of the custom Panda3D I had when I worked with this source a while ago. If I find it, I'll shoot you the link and hopefully it works out.

**Comment by toonjoey** [comment]
Thanks, would be fun 'cause I'm a TTI nerd (I'm working on a revival of the O:STT (Operation:Save Toontown) event, the least I've done is the TTC textures but those were lost).

**Comment by JohnathanUnknown** [comment]
You're welcome, and also it might be hard to remake the event when it *never* was released, and the information with it is hardly containing to the actual storyline.

**Comment by toonjoey** [comment]
AC-TU-AL-LEEEEE there's a document TTI posted that contained all the info that the event would "introduce" but since it was huge, and not worth it too much, I put it into a few phases.

**Comment by JohnathanUnknown** [comment]
Hmm, interesting.

**Comment by ToontownMango** [comment]
Does anyone have the resources? LOL I did but I deleted them rip

**Comment by toonjoey** [comment]
Just redownload the source...

**Comment by ToontownMango** [comment]
I'm confused, http://prntscr.com/batyhi

**Comment by JohnathanUnknown** [comment]
@ToontownMango Yeah, this repo didn't come with resources. 

Meh.

**Comment by toonjoey** [comment]
Thought it did, I have resources on mine :P

**Comment by JohnathanUnknown** [comment]
Odd, it'd be nice if resources were uploaded.. 

I'll try and find mine.

**Comment by toonjoey** [comment]
I have them but IDK where they're from.

**Comment by ToontownMango** [comment]
I don't mean to be rude, but by any chance can someone upload them to dropbox or something?
Edit:Saw Johnathans Post LOL

**Comment by JohnathanUnknown** [comment]
@toonjoey If possible, can you fork the repository and add the resources to your copy? 

That way you can submit a pull request and @ponyboy837 can merge it with the branch. 
*It'll solve hella lot of problems.*

**Comment by toonjoey** [comment]
Remember:They're off the magical valley of the interwebby. I can't remember where the heck they were from, nor how I got them TBH. I might as well.

**Comment by ToontownMango** [comment]
My friend gave me the resources but a couple of the phases .mf's were 1KB

**Comment by ToontownMango** [comment]
that's not normal LOL

**Comment by toonjoey** [comment]
t h i s  i s  f i n e

**Comment by ToontownMango** [comment]
?

**Comment by toonjoey** [comment]
holy crud i think i got it working

**Comment by ToontownMango** [comment]
Screenshot pls? Good Job!

**Comment by JohnathanUnknown** [comment]
Awesome. 

I actually kinda wanna work on this source tbh, might fork it and see what I can mess with.

**Comment by toonjoey** [comment]
OH WAIT NO HAHAHAHAHAHAHA
**HAHAHAHAHAHAHAHA**
Srsly I just copy pasted the files to "models" and it still didn't work. ;-;

**Comment by JohnathanUnknown** [comment]
Rest in peace toonjoey.

**Comment by toonjoey** [comment]
*insertundertalegameoverthemehere*
Jokes aside I'm gonna be off school tomorrow (Field trip but I didn't go) sooo yeeey.

**Comment by JohnathanUnknown** [comment]
Yeet.

**Comment by toonjoey** [comment]
wait
"Yeet."
Take the T off...
"Yee"
Yee was a feature in TTI source
I KNEW IT

**Comment by ToontownMango** [comment]
LOOOOL

**Comment by toonjoey** [comment]
Made edits to the good ol' boring thing that is the VP achievement names.
                     'VP Go Bye-bye',
                     '1-laff Survivor',
                     'Alonebot HQ',
                     'Going to the extremes'
VP Go Bye-bye is for defeating the HP, 1-laff survivor is self-explanatory, Alonebot HQ is soloing the VP, and Going to the extremes is soloing the VP with 1 laff.

**Comment by toonjoey** [comment]
Signing off for the night, g'night peoples.

**Comment by ToontownMango** [comment]
Alright, see you I'm going to probably eat then play TTR (maybe).

**Comment by ponyboy837** [comment]
Go ahead and fork it! I wont mind! Just give me and TTI credit for the source. Me for re-leaking it. TTI for making it

**Comment by ponyboy837** [comment]
Also the reason the src didn't come with resources as i didn't manage to get them when the leak happened.

**Comment by toonjoey** [comment]
I'm back. lol, Haven't gotten stuff done.

**Comment by toonjoey** [comment]
Also, by "resources" do you mean the ones from when the game was released for the 3rd(?) time?

**Comment by JohnathanUnknown** [comment]
Pretty sure he does.

**Comment by toonjoey** [comment]
Lemme try putting in the files from TTI in 2015. Hope it works...

**Comment by toonjoey** [comment]
One thing I hate is that I have a huge archive of unreleased TTI stuff. lol

**Comment by toonjoey** [comment]
Extracting right now! Once we launch this I'm gonna make the most accurate Toontown 2.0 "default" Toon (Periwinkle Dog) and go see if the revamped CFO is there. lol

**Comment by toonjoey** [comment]
So who else didn't get the Gooby effect in April Toons on TTI? I didn't because I was busy with datamining. lol

**Comment by toonjoey** [comment]
Still getting the "ToontownUberRepository has no attribute netMessenger", other than that it's fine.

**Comment by toonjoey** [comment]
AND IT STILL CANNOT LOAD THE CATALOG GUI

**Comment by toonjoey** [comment]
Well, I can't seem to load any of the files, which is strange considering I have the Panda3D TTI uses...

**Comment by JohnathanUnknown** [comment]
Hmmm..

**Comment by toonjoey** [comment]
It keeps loading the TTF files for me lol

**Comment by JohnathanUnknown** [comment]
*When* did TTF files ever get in here..? o_O

**Comment by toonjoey** [comment]
I was working with TTF source and it wouldn't work. .-.

**Comment by JohnathanUnknown** [comment]
Oh. .-.

Hmm.. The catalog GUI might be broken for now. *Can* you buy from it though? 
if so, maybe just try to brush it off and ignore the broken GUI. 

I found something on the netmessanger error, take a look:

> You do not have the proper Panda installation with net messenger. Its not supplied on this Github, but should be somewhere if you look hard enough. or you can make your own Panda 1.9.0 with Net messenger.

**Comment by toonjoey** [comment]
I feel trying to find NetMessenger is this: http://shitpostundertale.tumblr.com/image/143386282766

**Comment by JohnathanUnknown** [comment]
*Not UnderTale, please no..*

**Comment by toonjoey** [comment]
Undertale is a great game!

Its fanbase...
...is forbidden (at least like 2/3).

**Comment by JohnathanUnknown** [comment]
The fanbase is.. 

*Unspoken*

**Comment by toonjoey** [comment]
The fanbase is good, but a huge portion is terrifying, and that's the only thing people know about Undertale.

The fanbase can be great (Error!Sans, Bone Zone comic dubs, etc.), just unheard of.

**Comment by toonjoey** [comment]
Any luck on the Panda3D version?

**Comment by JohnathanUnknown** [comment]
Can't seem to find it, I'll try asking my ol' buddy Nick and see if he has it on him.

**Comment by toonjoey** [comment]
A sad thing about Toontown is that I tried getting TTR some steam by making a Sonic X-treme pack and this guy commented and said "toontown is shite, it's 12 years old and nobody cares about it".

That was the only comment I got. Needless to say I still made it.

**Comment by JohnathanUnknown** [comment]
Toontown is.. A *very* old game. 

However, care still exists. It may be "shite" now, but it was revolutionary back in the day. 
Also, when a massive Twitch streamer (sodapoppin) streams the game, what's that tell people?

*Oh yeah, the game still has steam in it.*

**Comment by toonjoey** [comment]
I'll see if I can find the thread, but when I stated some of those points he didn't respond and the thread was ded.

**Comment by JohnathanUnknown** [comment]
Guess he couldn't handle it.

**Comment by toonjoey** [comment]
http://www.sonic-xtreme.com/forums//viewtopic.php?id=957 Heres the thread, I started getting off topic in the OP lol

**Comment by JohnathanUnknown** [comment]
Ah :P

**Comment by toonjoey** [comment]
Has your friend Nick given any updates on the Panda3D thing?

**Comment by JohnathanUnknown** [comment]
Not yet, sadly.

**Comment by toonjoey** [comment]
Do you know where I can find the NetMessager BTW?

**Comment by JohnathanUnknown** [comment]
Not really sure, but I suggest you can ask around on Panda3D forums.

**Comment by toonjoey** [comment]
Just asked, waiting for an answer...

**Comment by toonjoey** [comment]
BTW did you guys know Panda3D was intended ONLY for Toontown? And that you can still find TTO remnants (besides level editor) in the files?

The only one I found so far is the GUI sounds (GUI_rollover and GUI_click(?))...

**Comment by JohnathanUnknown** [comment]
Actually, looking into this matter claims otherwise. 

Panda became widely used for Toontown, but it *not* directly made for the game. 
As a quote from Wikipedia, which was heavily influenced from research by contributors, Panda3D was made for..:

> The Disney VR studio is a branch of Disney that was created to build 3D attractions for Disney theme parks. They built an attraction called "Aladdin's Magic Carpet," and the engine they created for that eventually became Panda3D. The engine in its current form bears little resemblance to those early years. Over time, Panda3D was used for additional VR rides at Disney theme parks, and was eventually used in the creation of Toontown Online, an online game set in a cartoon world, and later for the second MMORPG, Pirates of the Caribbean Online.[4]

**Comment by JohnathanUnknown** [comment]
Wikipedia is not the only source I have, according to Revolvy.. They state the exact same thing. 

> http://www.revolvy.com/main/index.php?s=Panda3D
> https://en.wikipedia.org/wiki/Panda3D

^ Sources

**Comment by toonjoey** [comment]
Huh, I remember a post that was about the TT Editor not launching, and someone replied "How did you get it? Disney never released it." And then someone brought up the fact Panda3D was made for Toontown...

**Comment by JohnathanUnknown** [comment]
Who brought this up, exactly?

**Comment by toonjoey** [comment]
Can't remember at all, it was on the Panda3D forums.

**Comment by JohnathanUnknown** [comment]
Ah, alright.

**Comment by toonjoey** [comment]
Any updates?

**Comment by JohnathanUnknown** [comment]
Nick hasn't gotten on yet, so there's still no answer.

**Comment by JohnathanUnknown** [comment]
Same.

**Comment by toonjoey** [comment]
Until then lets chat about something.

I can't get this TTI 2016 leak to run...

**Comment by JohnathanUnknown** [comment]
Oh, 2016?

**Comment by toonjoey** [comment]
Yup, I got a link riiiiight...
...?
Did you see my link anywhere? I saw just now...



https://github.com/xJollibee/Toontown-Infinite-2016-Leak

**Comment by ponyboy837** [comment]
You might need a custom panda3d 1.10.0 which is what TTI began using. So i wouldn't be surprised

**Comment by JohnathanUnknown** [comment]
I think Nick has that *also*, since he has ran the source before with a copy of Panda-1.10.0.

**Comment by toonjoey** [comment]
OOOOOOOH! THAT'S WHY IT DIDN'T WORK!

.-.

**Comment by ponyboy837** [comment]
Yeah it'd explain alot.

**Comment by toonjoey** [comment]
Wait...
I have Panda3D since I got it from Toontown 2.0 by Spiderlover...

**Comment by ponyboy837** [comment]
lol

**Comment by toonjoey** [comment]
It just keeps saying "no module named __builtin__".

Woohoooo

**Comment by ponyboy837** [comment]
Rip lmao

**Comment by ponyboy837** [comment]
It's funny were talking by github and not something like skype

**Comment by JohnathanUnknown** [comment]
*10/10 GREAT ERROR* 

Must be something wrong with either the Panda or resources, kinda lazy to determine which right now.

**Comment by toonjoey** [comment]
Wait, what custom Panda3D do I need?

**Comment by ponyboy837** [comment]
A astron one for panda3d 1.10.0

**Comment by toonjoey** [comment]
Hmmmmmmm...

HRRRRRRRRRMMMMRBRBRBRBRBRB

**Comment by toonjoey** [comment]
How do I get a custom astron-panda3D-1.10.0?

**Comment by JohnathanUnknown** [comment]
Not sure.

**Comment by JohnathanUnknown** [comment]
I'll see (when he gets on) if Nick has it.

**Comment by toonjoey** [comment]
Dangit my dreams of playing the CFO are slightly-but-not-actually crushed

**Comment by JohnathanUnknown** [comment]
The 2016 link (examining it from xJollibee) doesn't seem to contain the new CFO.

**Comment by toonjoey** [comment]
Dangi-wait...then doesn't that mean its from 2014 or something?

**Comment by toonjoey** [comment]
If we can't load catalog_GUI.bam, there's another thing to do...
Disable it.

**Comment by JohnathanUnknown** [comment]
Sigh, errors man.

**Comment by ponyboy837** [comment]
Yeah. TTI fucks up alot. Wait my bad. 'did'

**Comment by JohnathanUnknown** [comment]
Meh, I have mutual respect for them. Considering it was the first server I ever played, and because I don't have time to go out of my way to *hate* them.

**Comment by toonjoey** [comment]
Well, you gotta give credit to them--they had features that could rival TTR by a **landslide!** I mean, guilds, new CFO, Factory rewards, you name it. They just couldn't keep the funds/determination long enough...

**Comment by JohnathanUnknown** [comment]
Had they kept going strong, I have a feeling they would've been a formidable rival.

**Comment by ponyboy837** [comment]
Yeah.

**Comment by toonjoey** [comment]
While we're waiting...
https://www.youtube.com/watch?v=FtxhSQiduMk

**Comment by ponyboy837** [comment]
It might

**Comment by ponyboy837** [comment]
Super Vinny Kart

**Comment by toonjoey** [comment]
Buttspoop is my name
Kart racing is my game

**Comment by ToontownMango** [comment]
im back, any progress?

**Comment by toonjoey** [comment]
Has anyone ever encountered someone who is offensive? And by offensive, I mean he/she's saying things like: "Kill yourself, fgt!"?

Also, ToontownMango, hOI!!!!!!!

**Comment by ponyboy837** [comment]
Yes

**Comment by ToontownMango** [comment]
@Joey19982 were talking about you :)

**Comment by ToontownMango** [comment]
jk

**Comment by toonjoey** [comment]
I have met a guy like who I described, he's on steam. He has 148 friends, and one is my best friend. he's always saying how Undertale is cancer. And when ANYONE disagrees with him he's like "kys"

I know it's fake TTM. :P

**Comment by JohnathanUnknown** [comment]
I formerly worked for Planet, and I can tell you.. 

Dauntless (current leader):
- Lies
- Trashtalks staff. 
- Steals code.

**Comment by JohnathanUnknown** [comment]
The competent staff left, leaving the incompetent ones to fight for themselves.

**Comment by ToontownMango** [comment]
I saw the TTE Exposed video, and  does dauntless work for TTE?

**Comment by JohnathanUnknown** [comment]
You wouldn't believe it, the reason "TTP is gone for a short time" is because.. 

The former staff and the current staff have beef. 
Planet would still be relevant had the compiler/main website developer not cut the cord on the website, rendering the launcher useless and wiping the website database clean. 

Also, he does not.

**Comment by ToontownMango** [comment]
So is this repo beyond repair (LOL)

**Comment by ToontownMango** [comment]
Back on Topic pls

**Comment by toonjoey** [comment]
Also Dauntless is (POSSIBLY) under the alias Weirdoguy101 on /r/Toontown, he's spreading more TTP advertisements. Like "Toontown Planet is better than Toontown Apex because Apex stole code from TTI.".

BTW, Apex didn't steal code from TTI, that was a joke leak by Rocky "Greening is Fun (S)Kids" Reborn.

ToontownMango, We're working on the repo right now.

**Comment by ToontownMango** [comment]
I would help, but I haz no resources.

**Comment by ToontownMango** [comment]
anyways brb.

**Comment by JohnathanUnknown** [comment]
@toonjoey I know who Weirdodude is, he is the main developer for one of my projects. 

He formerly advertised for Planet, but was one of the competent members who left. 
He was *also* the one who cut the cord on the website.

**Comment by toonjoey** [comment]
He was? HOLY CRUD! I never knew that...

**Comment by JohnathanUnknown** [comment]
#TheMoreYouKnow

**Comment by toonjoey** [comment]
http://prntscr.com/7u1691 Here's a pic of the leak I talked about when discussing Weirdodude.

**Comment by JohnathanUnknown** [comment]
O

**Comment by toonjoey** [comment]
If you still have it without the "firefox.exe" virus then you can hand it, I actually was 1/2 interested with it.

**Comment by ToontownMango** [comment]
Hey, some of the phases were missing in the GitHub,  did you supply your own?

**Comment by JohnathanUnknown** [comment]
Hmm?

**Comment by toonjoey** [comment]
Yup, they were just TTO phases.

Also Johnathan, it's the TTA leak we were discussing.

**Comment by ToontownMango** [comment]
I think I remember where I can download the TTO Phases

**Comment by ToontownMango** [comment]
hopefully

**Comment by toonjoey** [comment]
https://github.com/ToontownApex/Toontown-Apex Here's the source. Note it's not even the actual TTA source (Well from what I gather yes it is the source but it's not the real one .-.)

**Comment by ToontownMango** [comment]
https://github.com/StormyApps/Toontown-Testing  would these work?

**Comment by ToontownMango** [comment]
for the rest of the phases?

**Comment by toonjoey** [comment]
Wait, I stood corrected--TTI phases because this is supposedly "built" off TTI.

**Comment by ToontownMango** [comment]
it looks like TTI Retro and brb.

**Comment by toonjoey** [comment]
I get this when I start the game
Toontown Apex: Starting up.
Toontown Apex: Ready!
Toontown Apex: Starting game.
ToontownStart: setting default font
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File ".\toonbase\ToontownStart.py", line 80, in <module>
  File "toontown\toonbase\ToonBase.py", line 70, in __init__
    fullscreen = settings.get('fullscreen', False)
NameError: global name 'settings' is not defined

10/10 programming Rocky GG

**Comment by ToontownMango** [comment]
http://prntscr.com/bb6ce1

**Comment by ToontownMango** [comment]
Something wrong on your end.

**Comment by toonjoey** [comment]
HOW
DID
Y
O
U

**Comment by ToontownMango** [comment]
all i did was run the client.

**Comment by toonjoey** [comment]
I get "global name "settings" is not defined" still...

**Comment by toonjoey** [comment]
I used to get a "Could not find "ApexPhaseContent/phase_4/dna/toontown_central_sz.dna""

**Comment by ToontownMango** [comment]
idk why its working on my end.

**Comment by toonjoey** [comment]
I got it working...

**Comment by toonjoey** [comment]
Oh but wait now it needs to CONNECT

**Comment by toonjoey** [comment]
OH WAIT NVM! Time to enjoy a joke!

**Comment by ToontownMango** [comment]
it needs a pytz folder, ive used this source before. and it gave me a error about pytz

**Comment by toonjoey** [comment]
Oh right, I got mine from TTOff Squirting Flower

**Comment by toonjoey** [comment]
I can't delete Toons sadly...

**Comment by ToontownMango** [comment]
I know theres a away to fix it but i don't remember how.

**Comment by toonjoey** [comment]
Does anyone else have Steam? I'm gonna broadcast my playthrough of the game, and I want you guys to watch.

**Comment by ToontownMango** [comment]
no I don't.

**Comment by toonjoey** [comment]
What about Johnathan and ponyboy?

**Comment by ToontownMango** [comment]
idk, brb.

**Comment by toonjoey** [comment]
Broadcasting the TTA leak on Steam, just to show Rocky the joke he's found.

**Comment by toonjoey** [comment]
For some reason the battle tower exterior doesn't even load correctly lol.

**Comment by toonjoey** [comment]
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 613, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 620, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 160, in handleDatagram
    self.dbInterface.handleDatagram(msgType, di)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronDatabaseInterface.py", line 266, in handleDatagram
    self.handleQueryObjectResp(di)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronDatabaseInterface.py", line 136, in handleQueryObjectResp
    self._callbacks[ctx](dclass, fields)
  File ".\uberdog\ClientServicesManagerUD.py", line 494, in __handleRetrieve
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 279, in demand
    if not self.request(request, *args):
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 322, in request
    self.__setState(*result)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 457, in __setState
    self.__callEnterFunc(self.newState, *args)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 493, in __callEnterFunc
    func(*args)
  File ".\uberdog\ClientServicesManagerUD.py", line 600, in enterProcessDelete
KeyError: 'ACCOUNT_AV_SET_DEL'
:task(error): Exception occurred in PythonTask readerPollTask-62868440
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File ".\uberdog\ServiceStart.py", line 44, in <module>
  File "otp\ai\AIBase.py", line 179, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 613, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 620, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 160, in handleDatagram
    self.dbInterface.handleDatagram(msgType, di)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronDatabaseInterface.py", line 266, in handleDatagram
    self.handleQueryObjectResp(di)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronDatabaseInterface.py", line 136, in handleQueryObjectResp
    self._callbacks[ctx](dclass, fields)
  File ".\uberdog\ClientServicesManagerUD.py", line 494, in __handleRetrieve
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 279, in demand
    if not self.request(request, *args):
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 322, in request
    self.__setState(*result)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 457, in __setState
    self.__callEnterFunc(self.newState, *args)
  File "C:\Panda3D-1.9.0\direct\fsm\FSM.py", line 493, in __callEnterFunc
    func(*args)
  File ".\uberdog\ClientServicesManagerUD.py", line 600, in enterProcessDelete
KeyError: 'ACCOUNT_AV_SET_DEL'
Press any key to continue . . .
"I can program" - Rocky

**Comment by JohnathanUnknown** [comment]
Welp.

**Comment by toonjoey** [comment]
Do you have a Steam? I'm gonna play this game and broadcast it and I want you to watch.

**Comment by JohnathanUnknown** [comment]
I don't have one, sadly.

**Comment by toonjoey** [comment]
Dang, my friend isn't watching either (mainly from the offensive person I discussed earlier).

**Comment by toonjoey** [comment]
So in the Apex source do any of you know how to enable Cog HQs?

**Comment by JohnathanUnknown** [comment]
Haven't really investigated, so no.

**Comment by toonjoey** [comment]
I tried to enable them in the config, but they don't work.

**Comment by JohnathanUnknown** [comment]
Hmm..

**Comment by toonjoey** [comment]
I WANNA FIGHT THAT SCHWEEEEET CEO

**Comment by JohnathanUnknown** [comment]
*Schweeeeeeeeeeet*

**Comment by toonjoey** [comment]
teeeeeeeeeeewhcS

**Comment by toonjoey** [comment]
Really though, the revamped CEO looks cool and I wanna play it.

**Comment by JohnathanUnknown** [comment]
Yeah

**Comment by toonjoey** [comment]
I wonder if it even HAS the CEO...

**Comment by JohnathanUnknown** [comment]
The world may never know

**Comment by toonjoey** [comment]
Unless we convert PYC to PY

**Comment by JohnathanUnknown** [comment]
PYC is essentially a compiled version of a PY file, as you probably know. 

I doubt it'd be hard to convert them back to PY.

**Comment by toonjoey** [comment]
I can't...

**Comment by toonjoey** [comment]
And I have to go now, probably wont be back on.

**Comment by JohnathanUnknown** [comment]
Alright.

**Comment by toonjoey** [comment]
I'm back for a second .-.

**Comment by ponyboy837** [comment]
Lmao

**Comment by toonjoey** [comment]
Hi guys, I'm gonna give y'all freedom to do anything since I had a rough day. Don't worry 'bout me. :P

**Comment by toonjoey** [comment]
Good news:I think I may have found the correct Panda3D!

Bad news:THINK. I don't know...AT ALL really...soooo if it is then I'll go to my fork and make another pull request.

**Comment by toonjoey** [comment]
Guys
I FOUND IT

**Comment by toonjoey** [comment]
IT WORKS!
YES

**Comment by toonjoey** [comment]
GUYS I DID IT
I GOT IT WORKING

**Comment by toonjoey** [comment]
ALL RISE FOR OUR NATIONAL ANTHEMN!
https://www.youtube.com/watch?v=Hj5xvBLJxhs

**Comment by toonjoey** [comment]
oh
THE CATALOG DOESN'T WORK
LIKE I TOOOOTALLY DIDN'T WORK SOOOOOOOO HARD
TO HAVE SOMETHING NOT WORK

**Comment by toonjoey** [comment]
Ok guys, we're back to work since we're just one step from launching.

So far...
1.Yes, I have the correct Panda3D.
2.The only "wrong" thing with the source is that it can't find "catalog_GUI.bam".
3A.The source may/may not have the new CFO.
3B.The source may also have the boss tints.

**Comment by ToontownMango** [comment]
Is this one old than the one toontown gucci leaked i forgot he leaked 1.10.1 or something like that he leaked his around december.

**Comment by ToontownMango** [comment]
Also, the one he leaked, we would have to decompile the whole toontown folder, all of it is .pyc
and i know how to do it. but my pc is too slow.

**Comment by ToontownMango** [comment]
https://mega.nz/#!y8AwzKiY!p-ghpBaUZeMKVjWgyN1Ip4DrDszQSo_xyN1mMe5lehg
there it is incase you want to look at it.

**Comment by ToontownMango** [comment]
Also im decompiling it and zipping it up on my vps (the tti live leak from toontown gucci) ill put it on dropbox.

**Comment by toonjoey** [comment]
Just make sure you scan it to see if it has viruses--I'm not getting another virus on my computer.

**Comment by toonjoey** [comment]
Ok guys, I have bad news.

So, remember when Johnathan suggested we just disable the catalog? I tried...
Nope.

**Comment by toonjoey** [comment]
Uh...is everyone dead or something?

**Comment by toonjoey** [comment]
Also Toontown Mango, Apex source operated without .py, right?

**Comment by ToontownMango** [comment]
I broke my laptop I'm on my phone but yes to your question

**Comment by toonjoey** [comment]
Ok, so the same thing should happen.

Also, is it virus free?

**Comment by ToontownMango** [comment]
Yea.

Ok, so the same thing should happen.

Also, is it virus free?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ponyboy837/TTI-Leak--From-2015-/issues/1#issuecomment-224417096>,
or mute the thread
<https://github.com/notifications/unsubscribe/ASw5UwcKCMkZRLSEecckt_zS1EW_T5d2ks5qJd-0gaJpZM4Ij0KV>
.

**Comment by toonjoey** [comment]
Ok thanks.

And could you stop displaying the e-mail? lol

**Comment by toonjoey** [comment]
Ok, got the gucci source. It doesn't have any files to launch it. Good job my man. lol

It's now obviously an attempt to lie to us.

**Comment by ponyboy837** [comment]
This source is? No this isn't that Gucci shit it's a dev build. Get facts straight.

**Comment by toonjoey** [comment]
Ok, for now we should say something.

We know that the main fault is a programming oversight in the catalog code--it's not able to find phase 3s "catalog_GUI".

I was talking about that, should've clarified. lol

**Comment by ponyboy837** [comment]
Ok

**Comment by toonjoey** [comment]
I tried saying that the directory is "../../resources/phase_3" etc., but that doesn't work...

**Comment by toonjoey** [comment]
Meh, I'm running out of fixes here so I'm gonna comment all code in CatalogGlobals. If anyone has found a fix then tell me ASAP.

**Comment by toonjoey** [comment]
That didn't work...DELETE THE FILES?

Gee I surely am running out of ideas.

**Comment by toonjoey** [comment]
That didn't work (duh)...I don't think there's a way to fix it, nor will there be.

*sigh*

**Comment by toonjoey** [comment]
Now I'm getting this:
Username:
===============================
Starting Toontown Infinite...
ppython: C:/Panda3D-1.9.0/python/python.exe
Username:
Gameserver: 127.0.0.1
===============================
:ClientStart: Reading preferences.json...
:ClientStart: Starting the game...
:ClientStart: Setting the default font...
TTLocalizer: Running in language: english
OTPLocalizer: Running in language: english
Known pipe types:
  wglGraphicsPipe
(2 aux display modules not yet loaded.)
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
:audio(error): OpenALAudioManager: alcOpenDevice(NULL): ALC couldn't open device
:audio(error): OpenALAudioManager: No open device or context
Press any key to continue . . .

Now that's just messed up.

**Comment by toonjoey** [comment]
It fixed itself...
SAME CATALOG ERROR.

OH BOY! DON'T YOU LOVE IT WHEN THE SAME ERROR HAPPENS WHEN YOU THINK YOU FIX IT?!

**Comment by toonjoey** [comment]
*poof* Everyone dead? I'm here lol
